import { useEffect, useMemo, useState } from 'react'
import { useApp } from '../store'
import { BARRIOS, COMUNAS, CORREGIMIENTOS, INTERESES, GRUPOS_SOCIALES, OCUPACIONES, PROFESIONES, NIVELES_ACADEMICOS, POSGRADOS, MUNICIPIO_CAMPANA } from '../data'
import { useCatalogos } from '../catalogos'
import { ROL_SIMPATIZANTE_LABEL } from '../types'
import type { EstadoCampana, PersonaInput, RolDiaE, RolSimpatizante, SimpatizanteApi } from '../types'

const ESTADOS: EstadoCampana[] = ['Activo', 'Inactivo', 'Retirado', 'Fallecido']

const input='w-full rounded-lg border border-gray-300 px-2.5 py-1.5 text-sm outline-none focus:border-blue-500 disabled:bg-gray-100 disabled:text-gray-400'
const empty:PersonaInput={nombres:'',apellidos:'',cedula:'',fechaNacimiento:'',telefono:'',correo:'',direccion:'',departamento:'Cesar',municipio:'Valledupar',zona:'Urbana',comuna:'',corregimiento:'',barrio:'',puesto:'',mesa:1,intereses:[],gruposSociales:[],ocupacion:'',profesion:'Sin estudios',nivelAcademico:'Sin estudios',posgrado:'Ninguno',observacion:'',vehiculos:[],liderId:'',nivelVoto:'Firme',rolDiaE:'Votante',habeasData:false,estado:'Activo'}
const toForm=(p:SimpatizanteApi):PersonaInput=>({...empty,nombres:p.nombres,apellidos:p.apellidos,cedula:p.cedula,fechaNacimiento:p.fechaNacimiento??'',telefono:p.telefono??'',correo:p.correo??'',direccion:p.direccion??'',departamento:p.departamento??'Cesar',municipio:p.municipio??'',zona:p.zona??'Urbana',comuna:p.comuna??'',corregimiento:p.corregimiento??'',barrio:p.barrio??'',puesto:p.puesto??'',mesa:p.mesa??1,intereses:[...p.intereses],gruposSociales:[...p.gruposSociales],ocupacion:p.ocupacion??'',profesion:p.profesion??'',nivelAcademico:p.nivelAcademico,posgrado:p.posgrado,observacion:p.observacion??'',vehiculos:p.vehiculos.map(v=>({...v})),liderId:p.liderId,nivelVoto:p.nivelVoto,rolDiaE:p.rolDiaE,habeasData:p.habeasData,planillaCodigo:p.planillaCodigo??'',estado:p.estado??'Activo'})
// Incluye el valor guardado aunque no exista en el catálogo, para que el select lo muestre al editar
const conValor=(list:string[],v:string|undefined)=>v&&!list.includes(v)?[v,...list]:list
// req: campo obligatorio (lo exige el backend o la base de datos) — se marca con * rojo.
const Field=({label,children,wide=false,req=false}:{label:string;children:React.ReactNode;wide?:boolean;req?:boolean})=><label className={wide?'col-span-2':''}><span className="mb-1 block text-xs font-medium text-gray-500">{label}{req&&<span className="ml-0.5 text-red-500">*</span>}</span>{children}</label>
const Select=({value,onChange,children,required=false,disabled=false}:{value:string|undefined;onChange:(v:string)=>void;children:React.ReactNode;required?:boolean;disabled?:boolean})=><select required={required} disabled={disabled} className={input} value={value??''} onChange={e=>onChange(e.target.value)}>{children}</select>
function Tags({title,values,selected,toggle}:{title:string;values:string[];selected:string[];toggle:(v:string)=>void}){return <div className="mt-4"><p className="mb-2 text-xs font-medium text-gray-500">{title}</p><div className="flex flex-wrap gap-2">{values.map(v=><button key={v} type="button" onClick={()=>toggle(v)} className={`rounded-full border px-3 py-1 text-xs font-medium ${selected.includes(v)?'border-blue-600 bg-blue-50 text-blue-700':'border-gray-300 text-gray-600 hover:bg-gray-50'}`}>{v}</button>)}</div></div>}
export default function PersonaForm(){
 const {personaModal,closePersona,savePersona,cargarSimpatizanteDetalle,cambiarRolSimpatizante,session,navigate,lideresApi:rawLideresApi}=useApp(); const cat=useCatalogos(); const [form,setForm]=useState<PersonaInput>(empty); const lideresApi=rawLideresApi.filter(l=>l.activo||l.id===form.liderId); const liderPropio=session?.rol==='lider'?rawLideresApi.find(l=>l.userId===session.id):undefined; const [busy,setBusy]=useState(false); const [cargando,setCargando]=useState(false); const [votacion,setVotacion]=useState<{dpto:string;munic:string}>({dpto:'Cesar',munic:MUNICIPIO_CAMPANA}); const [rol,setRol]=useState<{actual:RolSimpatizante;nuevo:RolSimpatizante}>({actual:'simpatizante',nuevo:'simpatizante'})
 const editando=personaModal?.mode==='edit'&&!!personaModal.personaId
 const puedeCambiarRol=editando&&session?.rol==='admin'
 useEffect(()=>{if(!personaModal)return; setVotacion({dpto:'Cesar',munic:MUNICIPIO_CAMPANA}); setRol({actual:'simpatizante',nuevo:'simpatizante'}); if(personaModal.mode==='edit'&&personaModal.personaId){setCargando(true); void cargarSimpatizanteDetalle(personaModal.personaId).then(p=>{if(p){setForm(toForm(p));setVotacion({dpto:p.departamentoVotacion??(p.puesto?'':'Cesar'),munic:p.municipioVotacion??(p.puesto?'':MUNICIPIO_CAMPANA)});setRol({actual:p.rol,nuevo:p.rol})} setCargando(false)})}else setForm({...empty,liderId:liderPropio?.id??''})
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[personaModal])
 const set=<K extends keyof PersonaInput>(k:K,v:PersonaInput[K])=>setForm(f=>({...f,[k]:v}))
 // Puestos activos del departamento/municipio de votación elegidos (más el guardado, aunque esté inactivo).
 const puestos=useMemo(()=>cat.puestos.filter(p=>(p.activo||p.codigo===form.puesto)&&(!votacion.dpto||p.departamento===votacion.dpto)&&(!votacion.munic||p.municipio===votacion.munic)),[cat.puestos,votacion,form.puesto]); if(!personaModal)return null
 const puesto=cat.puestos.find(p=>p.codigo===form.puesto)
 // Sin catálogo cargado (antes de la migración 028) se ofrecen los valores conocidos.
 const deptos=cat.departamentos.length?cat.departamentos:['Cesar']; const munics=(d:string)=>cat.departamentos.length?cat.municipiosDe(d):['Valledupar','La Paz','San Diego']
 const esCampana=form.municipio===MUNICIPIO_CAMPANA
 const setSector=(v:string)=>setForm(f=>CORREGIMIENTOS.includes(v)?{...f,zona:'Rural',corregimiento:v,comuna:''}:{...f,zona:'Urbana',comuna:v,corregimiento:''})
 const elegirPuesto=(v:string)=>{const p=cat.puestos.find(x=>x.codigo===v); setForm(f=>({...f,puesto:v,mesa:p&&f.mesa&&f.mesa<=p.mesas?f.mesa:1})); if(p)setVotacion({dpto:p.departamento,munic:p.municipio})}
 const mesas=Math.max(puesto?.mesas??0,form.puesto?form.mesa??0:0); const toggle=(k:'intereses'|'gruposSociales',v:string)=>set(k,form[k].includes(v)?form[k].filter(x=>x!==v):[...form[k],v] as never)
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{if(puedeCambiarRol&&rol.nuevo!==rol.actual&&!(await cambiarRolSimpatizante(personaModal!.personaId!,rol.nuevo)))return;await savePersona({...form,liderId:liderPropio?.id??form.liderId,mesa:(form.puesto?form.mesa:null) as number,departamentoVotacion:votacion.dpto||null,municipioVotacion:votacion.munic||null,rolDiaE:form.rolDiaE as RolDiaE})}finally{setBusy(false)}}
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="max-h-[90vh] w-full max-w-6xl overflow-y-auto rounded-2xl bg-white shadow-xl"><div className="flex items-center justify-between border-b border-gray-200 px-6 py-4"><h2 className="text-lg font-semibold text-gray-900">{editando?'Editar Simpatizante':'Nuevo Simpatizante'}</h2><button type="button" onClick={closePersona} className="text-gray-400">✕</button></div>{cargando?<p className="px-6 py-10 text-center text-sm text-gray-400">Cargando ficha…</p>:<form onSubmit={submit} className="space-y-6 px-6 py-5">
 <section><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-blue-700">1 · Datos personales</p><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{(['nombres','apellidos','cedula','telefono'] as const).map(k=><Field key={k} req label={{nombres:'Nombres',apellidos:'Apellidos',cedula:'Cédula',telefono:'Teléfono'}[k]}><input required disabled={session?.rol==='gestor'&&editando} title={session?.rol==='gestor'&&editando?'Dato de identidad: repórtalo a tu líder o al administrador':undefined} className={input} value={form[k]} onChange={e=>set(k,e.target.value)}/></Field>)}<Field label="Correo" wide><input className={input} type="email" value={form.correo} onChange={e=>set('correo',e.target.value)}/></Field></div></section>
 <section><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-blue-700">2 · Ubicación — Residencia</p><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Field label="Departamento" req><Select required value={form.departamento} onChange={v=>setForm(f=>({...f,departamento:v,municipio:'',comuna:'',corregimiento:'',barrio:''}))}><option value="">Seleccionar</option>{conValor(deptos,form.departamento).map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Municipio" req><Select required value={form.municipio} onChange={v=>setForm(f=>({...f,municipio:v,zona:'Urbana',comuna:'',corregimiento:'',barrio:''}))}><option value="">Seleccionar</option>{conValor(munics(form.departamento),form.municipio).map(x=><option key={x}>{x}</option>)}</Select></Field>{esCampana?<><Field label="Comuna/Corregimiento" req><Select required value={form.zona==='Rural'?form.corregimiento:form.comuna} onChange={setSector}><option value="">Seleccionar</option>{conValor([...COMUNAS,...CORREGIMIENTOS],form.zona==='Rural'?form.corregimiento:form.comuna).map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Barrio" req><Select required value={form.barrio} onChange={v=>set('barrio',v)}><option value="">Seleccionar</option>{conValor(BARRIOS,form.barrio).map(x=><option key={x}>{x}</option>)}</Select></Field></>:<><Field label="Comuna/Corregimiento" req><input required className={input} value={form.zona==='Rural'?form.corregimiento:form.comuna} onChange={e=>form.zona==='Rural'?set('corregimiento',e.target.value):set('comuna',e.target.value)}/></Field><Field label="Barrio" req><input required className={input} value={form.barrio} onChange={e=>set('barrio',e.target.value)}/></Field></>}</div></section>
 <section><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-blue-700">3 · Puesto de Votación</p><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Field label="Dpto-Votación"><Select value={votacion.dpto} onChange={v=>{setVotacion({dpto:v,munic:''});setForm(f=>({...f,puesto:''}))}}><option value="">Seleccionar</option>{conValor(deptos,votacion.dpto).map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Munic-Votación"><Select value={votacion.munic} onChange={v=>{setVotacion(x=>({...x,munic:v}));setForm(f=>({...f,puesto:''}))}}><option value="">Seleccionar</option>{conValor(munics(votacion.dpto),votacion.munic).map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Pto-Votación" wide><Select value={form.puesto} onChange={elegirPuesto}><option value="">Sin asignar</option>{form.puesto&&!puesto&&<option value={form.puesto}>{form.puesto}</option>}{puestos.map(p=><option key={p.codigo} value={p.codigo}>{p.nombre} ({p.codigo}){p.activo?'':' — inactivo'}</option>)}</Select>{session?.rol==='admin'&&<button type="button" onClick={()=>{closePersona();navigate('puestos')}} className="mt-1 text-[11px] font-medium text-blue-600 hover:underline">+ Agregar o editar puestos de votación</button>}</Field><Field label="Mesa-Votación"><Select disabled={!form.puesto} value={form.puesto?String(form.mesa??''):''} onChange={v=>set('mesa',Number(v))}>{form.puesto&&mesas>0?Array.from({length:mesas},(_,i)=>i+1).map(n=><option key={n} value={n}>Mesa {n}</option>):<option value="">Sin asignar</option>}</Select></Field></div>{form.puesto&&puestos.length===0&&<p className="mt-1 text-[11px] text-amber-700">No hay puestos registrados para ese municipio.</p>}</section>
 <section><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-blue-700">4 · Caracterización Social</p><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Field label="Ocupación (actual)"><Select value={form.ocupacion} onChange={v=>set('ocupacion',v)}><option value="">Sin dato</option>{OCUPACIONES.map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Profesión"><Select value={form.profesion} onChange={v=>set('profesion',v)}><option value="">Sin dato</option>{PROFESIONES.map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Nivel académico"><Select value={form.nivelAcademico} onChange={v=>set('nivelAcademico',v as PersonaInput['nivelAcademico'])}>{NIVELES_ACADEMICOS.map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Posgrado"><Select value={form.posgrado} onChange={v=>set('posgrado',v as PersonaInput['posgrado'])}>{POSGRADOS.map(x=><option key={x}>{x}</option>)}</Select></Field></div><Tags title="Gustos e Intereses" values={INTERESES} selected={form.intereses} toggle={v=>toggle('intereses',v)}/><Tags title="Grupos sociales" values={GRUPOS_SOCIALES} selected={form.gruposSociales} toggle={v=>toggle('gruposSociales',v)}/><div className="mt-4"><Field label="Observación (datos adicionales)"><textarea className={`${input} min-h-[70px] resize-y`} placeholder="Cualquier dato adicional del simpatizante…" value={form.observacion} onChange={e=>set('observacion',e.target.value)}/></Field></div></section>
 {puedeCambiarRol&&<section><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-blue-700">Rol en la campaña</p><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Field label="Rol"><Select value={rol.nuevo} onChange={v=>setRol(r=>({...r,nuevo:v as RolSimpatizante}))}>{(Object.keys(ROL_SIMPATIZANTE_LABEL) as RolSimpatizante[]).map(r=><option key={r} value={r}>{ROL_SIMPATIZANTE_LABEL[r]}</option>)}</Select></Field></div><p className="mt-1 text-[11px] text-gray-400">Todos votan, independiente del rol. El rol lo clasifica y le da funciones.</p></section>}
 <section><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-blue-700">5 · Logística Día "E" (Vehículos)</p><label className="flex items-center gap-2 text-sm text-gray-700"><input type="checkbox" checked={form.vehiculos.length>0} onChange={e=>set('vehiculos',e.target.checked?[{tipo:'Moto',capacidadPasajeros:1,aDisposicion:true,estado:'Disponible'}]:[])}/>¿Tiene vehículo(s) disponible(s) para la campaña?</label><p className="mt-1 text-xs text-gray-400">Una persona puede ofrecer más de uno (ej. moto y carro a la vez).</p></section>
 <section><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-blue-700">6 · Vinculación y Compromiso</p><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Field label="Líder asignado" req={rol.actual!=='padrino'}>{liderPropio?<input disabled className={input} value={`${liderPropio.nombres} ${liderPropio.apellidos}`}/>:<Select required={rol.actual!=='padrino'} value={form.liderId} onChange={v=>set('liderId',v)}><option value="">Seleccionar</option>{lideresApi.map(l=><option key={l.id} value={l.id}>{l.nombres} {l.apellidos}</option>)}</Select>}</Field><Field label="Nivel de voto"><Select required value={form.nivelVoto} onChange={v=>set('nivelVoto',v as PersonaInput['nivelVoto'])}><option>Firme</option><option>Indeciso</option></Select></Field><Field label="Rol asignado Día E"><Select required value={form.rolDiaE} onChange={v=>set('rolDiaE',v as RolDiaE)}><option>Votante</option><option>Conductor</option><option>Testigo electoral</option></Select></Field><Field label="¿Ya votó? (Día E)"><label className="flex h-[34px] items-center gap-2 rounded-lg border border-gray-300 px-2.5 text-sm text-gray-400"><input disabled type="checkbox"/>Aún no</label><p className="mt-1 text-[11px] text-gray-400">Se habilita el 15/09/2026.</p></Field></div></section>
 <section><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-blue-700">7 · Estado en la Campaña</p><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Field label="Estado" req><Select required value={form.estado} onChange={v=>set('estado',v as EstadoCampana)}>{ESTADOS.map(x=><option key={x}>{x}</option>)}</Select></Field></div><p className="mt-1 text-[11px] text-gray-400">Inactivo, Retirado o Fallecido: la persona se conserva en la base, pero ya no cuenta como voto activo de la campaña.</p></section>
 <section><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-blue-700">8 · Habeas Data</p><label className="flex items-start gap-2 text-sm text-gray-700"><input type="checkbox" required checked={form.habeasData} onChange={e=>set('habeasData',e.target.checked)} className="mt-0.5"/><span>El simpatizante autoriza el tratamiento de sus datos personales (Ley 1581 de 2012). <span className="text-red-500">*</span></span></label></section>
 <div className="flex justify-end gap-3 border-t border-gray-100 pt-4"><button type="button" onClick={closePersona} className="rounded-lg border border-gray-300 px-4 py-2 text-sm">Cancelar</button><button disabled={busy} type="submit" className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">{busy?'Guardando…':editando?'Guardar cambios':'Crear Simpatizante'}</button></div></form>}</div></div>
}
