import { useEffect, useMemo, useState } from 'react'
import { useApp } from '../store'
import { BARRIOS, COMUNAS, CORREGIMIENTOS, INTERESES, GRUPOS_SOCIALES, OCUPACIONES, PROFESIONES, PUESTOS, NIVELES_ACADEMICOS, POSGRADOS } from '../data'
import { ROL_SIMPATIZANTE_LABEL } from '../types'
import type { PersonaInput, RolDiaE, RolSimpatizante, SimpatizanteApi } from '../types'

const input='w-full rounded-lg border border-gray-300 px-2.5 py-1.5 text-sm outline-none focus:border-blue-500 disabled:bg-gray-100 disabled:text-gray-400'
const empty:PersonaInput={nombres:'',apellidos:'',cedula:'',fechaNacimiento:'',telefono:'',correo:'',direccion:'',departamento:'Cesar',municipio:'Valledupar',zona:'Urbana',comuna:'',corregimiento:'',barrio:'',puesto:'',mesa:1,intereses:[],gruposSociales:[],ocupacion:'',profesion:'Sin estudios',nivelAcademico:'Sin estudios',posgrado:'Ninguno',observacion:'',vehiculos:[],liderId:'',nivelVoto:'Firme',rolDiaE:'Votante',habeasData:false}
const toForm=(p:SimpatizanteApi):PersonaInput=>({...empty,nombres:p.nombres,apellidos:p.apellidos,cedula:p.cedula,fechaNacimiento:p.fechaNacimiento??'',telefono:p.telefono??'',correo:p.correo??'',direccion:p.direccion??'',departamento:p.departamento??'Cesar',municipio:p.municipio??'',zona:p.zona??'Urbana',comuna:p.comuna??'',corregimiento:p.corregimiento??'',barrio:p.barrio??'',puesto:p.puesto??'',mesa:p.mesa??1,intereses:[...p.intereses],gruposSociales:[...p.gruposSociales],ocupacion:p.ocupacion??'',profesion:p.profesion??'',nivelAcademico:p.nivelAcademico,posgrado:p.posgrado,observacion:p.observacion??'',vehiculos:p.vehiculos.map(v=>({...v})),liderId:p.liderId,nivelVoto:p.nivelVoto,rolDiaE:p.rolDiaE,habeasData:p.habeasData,planillaCodigo:p.planillaCodigo??''})
// Incluye el valor guardado aunque no exista en el catálogo, para que el select lo muestre al editar
const conValor=(list:string[],v:string|undefined)=>v&&!list.includes(v)?[v,...list]:list
const Field=({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean})=><label className={wide?'col-span-2':''}><span className="mb-1 block text-xs font-medium text-gray-500">{label}</span>{children}</label>
const Select=({value,onChange,children,required=false}:{value:string|undefined;onChange:(v:string)=>void;children:React.ReactNode;required?:boolean})=><select required={required} className={input} value={value??''} onChange={e=>onChange(e.target.value)}>{children}</select>
function Tags({title,values,selected,toggle}:{title:string;values:string[];selected:string[];toggle:(v:string)=>void}){return <div className="mt-4"><p className="mb-2 text-xs font-medium text-gray-500">{title}</p><div className="flex flex-wrap gap-2">{values.map(v=><button key={v} type="button" onClick={()=>toggle(v)} className={`rounded-full border px-3 py-1 text-xs font-medium ${selected.includes(v)?'border-blue-600 bg-blue-50 text-blue-700':'border-gray-300 text-gray-600 hover:bg-gray-50'}`}>{v}</button>)}</div></div>}
export default function PersonaForm(){
 const {personaModal,closePersona,savePersona,cargarSimpatizanteDetalle,cambiarRolSimpatizante,session,lideresApi:rawLideresApi}=useApp(); const [form,setForm]=useState<PersonaInput>(empty); const lideresApi=rawLideresApi.filter(l=>l.activo||l.id===form.liderId); const [busy,setBusy]=useState(false); const [cargando,setCargando]=useState(false); const [votacion,setVotacion]=useState<{dpto:string|null;munic:string|null}>({dpto:null,munic:null}); const [rol,setRol]=useState<{actual:RolSimpatizante;nuevo:RolSimpatizante}>({actual:'simpatizante',nuevo:'simpatizante'})
 const editando=personaModal?.mode==='edit'&&!!personaModal.personaId
 const puedeCambiarRol=editando&&session?.rol==='admin'
 useEffect(()=>{if(!personaModal)return; setVotacion({dpto:null,munic:null}); setRol({actual:'simpatizante',nuevo:'simpatizante'}); if(personaModal.mode==='edit'&&personaModal.personaId){setCargando(true); void cargarSimpatizanteDetalle(personaModal.personaId).then(p=>{if(p){setForm(toForm(p));setVotacion({dpto:p.departamentoVotacion,munic:p.municipioVotacion});setRol({actual:p.rol,nuevo:p.rol})} setCargando(false)})}else setForm(empty)
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[personaModal])
 const set=<K extends keyof PersonaInput>(k:K,v:PersonaInput[K])=>setForm(f=>({...f,[k]:v})); const puestos=useMemo(()=>PUESTOS.filter(p=>p.municipio===form.municipio),[form.municipio]); if(!personaModal)return null
 const puesto=puestos.find(p=>p.id===form.puesto); const toggle=(k:'intereses'|'gruposSociales',v:string)=>set(k,form[k].includes(v)?form[k].filter(x=>x!==v):[...form[k],v] as never)
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{if(puedeCambiarRol&&rol.nuevo!==rol.actual&&!(await cambiarRolSimpatizante(personaModal!.personaId!,rol.nuevo)))return;await savePersona({...form,mesa:puesto?.mesaBase??form.mesa,rolDiaE:form.rolDiaE as RolDiaE})}finally{setBusy(false)}}
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="max-h-[90vh] w-full max-w-6xl overflow-y-auto rounded-2xl bg-white shadow-xl"><div className="flex items-center justify-between border-b border-gray-200 px-6 py-4"><h2 className="text-lg font-semibold text-gray-900">{editando?'Editar Simpatizante':'Nuevo Simpatizante'}</h2><button type="button" onClick={closePersona} className="text-gray-400">✕</button></div>{cargando?<p className="px-6 py-10 text-center text-sm text-gray-400">Cargando ficha…</p>:<form onSubmit={submit} className="space-y-6 px-6 py-5">
 <section><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-blue-700">1 · Datos personales</p><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{(['nombres','apellidos','cedula','telefono'] as const).map(k=><Field key={k} label={{nombres:'Nombres',apellidos:'Apellidos',cedula:'Cédula',telefono:'Teléfono'}[k]}><input required={k!=='telefono'} className={input} value={form[k]} onChange={e=>set(k,e.target.value)}/></Field>)}<Field label="Correo" wide><input className={input} type="email" value={form.correo} onChange={e=>set('correo',e.target.value)}/></Field></div></section>
 <section><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-blue-700">2 · Ubicación — Residencia</p><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Field label="Departamento"><input disabled className={input} value="Cesar"/></Field><Field label="Municipio"><Select value={form.municipio} onChange={v=>set('municipio',v)}><option value="">Seleccionar</option>{conValor(['Valledupar','La Paz','San Diego'],form.municipio).map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Comuna/Corregimiento"><Select value={form.zona==='Rural'?form.corregimiento:form.comuna} onChange={v=>form.zona==='Rural'?set('corregimiento',v):set('comuna',v)}><option value="">Seleccionar</option>{conValor([...COMUNAS,...CORREGIMIENTOS],form.zona==='Rural'?form.corregimiento:form.comuna).map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Barrio"><Select value={form.barrio} onChange={v=>set('barrio',v)}><option value="">Seleccionar</option>{conValor(BARRIOS,form.barrio).map(x=><option key={x}>{x}</option>)}</Select></Field></div></section>
 <section><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-blue-700">3 · Puesto de Votación</p><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Field label="Pto-Votación" wide><Select value={form.puesto} onChange={v=>set('puesto',v)}><option value="">Sin asignar</option>{form.puesto&&!puesto&&<option value={form.puesto}>{form.puesto}</option>}{puestos.map(p=><option key={p.id} value={p.id}>{p.nombre} ({p.municipio})</option>)}</Select></Field><Field label="Dpto-Votación"><input disabled className={input} value={puesto?.departamento??votacion.dpto??'—'}/></Field><Field label="Munic-Votación"><input disabled className={input} value={puesto?.municipio??votacion.munic??'—'}/></Field><Field label="Mesa-Votación"><select disabled className={input}><option>{puesto?.mesaBase??(form.puesto?form.mesa:'Sin asignar')}</option></select></Field></div></section>
 <section><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-blue-700">4 · Caracterización Social</p><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Field label="Ocupación (actual)"><Select value={form.ocupacion} onChange={v=>set('ocupacion',v)}><option value="">Sin dato</option>{OCUPACIONES.map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Profesión"><Select value={form.profesion} onChange={v=>set('profesion',v)}><option value="">Sin dato</option>{PROFESIONES.map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Nivel académico"><Select value={form.nivelAcademico} onChange={v=>set('nivelAcademico',v as PersonaInput['nivelAcademico'])}>{NIVELES_ACADEMICOS.map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Posgrado"><Select value={form.posgrado} onChange={v=>set('posgrado',v as PersonaInput['posgrado'])}>{POSGRADOS.map(x=><option key={x}>{x}</option>)}</Select></Field></div><Tags title="Gustos e Intereses" values={INTERESES} selected={form.intereses} toggle={v=>toggle('intereses',v)}/><Tags title="Grupos sociales" values={GRUPOS_SOCIALES} selected={form.gruposSociales} toggle={v=>toggle('gruposSociales',v)}/><div className="mt-4"><Field label="Observación (datos adicionales)"><textarea className={`${input} min-h-[70px] resize-y`} placeholder="Cualquier dato adicional del simpatizante…" value={form.observacion} onChange={e=>set('observacion',e.target.value)}/></Field></div></section>
 {puedeCambiarRol&&<section><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-blue-700">Rol en la campaña</p><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Field label="Rol"><Select value={rol.nuevo} onChange={v=>setRol(r=>({...r,nuevo:v as RolSimpatizante}))}>{(Object.keys(ROL_SIMPATIZANTE_LABEL) as RolSimpatizante[]).map(r=><option key={r} value={r}>{ROL_SIMPATIZANTE_LABEL[r]}</option>)}</Select></Field></div><p className="mt-1 text-[11px] text-gray-400">Todos votan, independiente del rol. El rol lo clasifica y le da funciones.</p></section>}
 <section><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-blue-700">5 · Logística Día "E" (Vehículos)</p><label className="flex items-center gap-2 text-sm text-gray-700"><input type="checkbox" checked={form.vehiculos.length>0} onChange={e=>set('vehiculos',e.target.checked?[{tipo:'Moto',capacidadPasajeros:1,aDisposicion:true,estado:'Disponible'}]:[])}/>¿Tiene vehículo(s) disponible(s) para la campaña?</label><p className="mt-1 text-xs text-gray-400">Una persona puede ofrecer más de uno (ej. moto y carro a la vez).</p></section>
 <section><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-blue-700">6 · Vinculación y Compromiso</p><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Field label="Líder asignado"><Select required={rol.actual!=='padrino'} value={form.liderId} onChange={v=>set('liderId',v)}><option value="">Seleccionar</option>{lideresApi.map(l=><option key={l.id} value={l.id}>{l.nombres} {l.apellidos}</option>)}</Select></Field><Field label="Nivel de voto"><Select required value={form.nivelVoto} onChange={v=>set('nivelVoto',v as PersonaInput['nivelVoto'])}><option>Firme</option><option>Indeciso</option></Select></Field><Field label="Rol asignado Día E"><Select required value={form.rolDiaE} onChange={v=>set('rolDiaE',v as RolDiaE)}><option>Votante</option><option>Testigo Electoral</option><option>Transportador</option><option>Logística</option><option>Coordinador de Puesto</option></Select></Field><Field label="¿Ya votó? (Día E)"><label className="flex h-[34px] items-center gap-2 rounded-lg border border-gray-300 px-2.5 text-sm text-gray-400"><input disabled type="checkbox"/>Aún no</label><p className="mt-1 text-[11px] text-gray-400">Se habilita el 15/09/2026.</p></Field></div></section>
 <div className="flex justify-end gap-3 border-t border-gray-100 pt-4"><button type="button" onClick={closePersona} className="rounded-lg border border-gray-300 px-4 py-2 text-sm">Cancelar</button><button disabled={busy} type="submit" className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">{busy?'Guardando…':editando?'Guardar cambios':'Crear Simpatizante'}</button></div></form>}</div></div>
}
