import { ArrowRight, CircleHelp, Flag, Map, Users } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useApp } from '../../../store'
import Directorio from '../../simpatizantes/pages/DirectorioPage'

const barrios = ['San Martín', 'Rincón de Ziruma', 'Los Ángeles', 'San Francisco', 'San Isidro', 'Villa del Rosario', 'El Prado', 'El Cerrito', 'La Nevada', 'Mayales']
const coloresBarrios = ['#2563eb', '#7c3aed', '#0d9488', '#f59e0b', '#dc2626', '#059669', '#db2777', '#4f46e5', '#65a30d', '#0891b2']
const lideres = [
  ['Alberto Armendáriz Vera', 106, 100, 6, '22%', 'Amarillo'], ['Marilú Ojeda Soliz', 72, 65, 7, '31%', 'Amarillo'], ['Gabriel Abrego Rivera', 34, 30, 4, '40%', 'Amarillo'], ['Norma Solano Naranjo', 13, 10, 3, '20%', 'Amarillo'], ['María Alejandro Lira', 12, 9, 3, '44%', 'Amarillo'], ['Olivia Flórez Olivares', 18, 8, 10, '38%', 'Amarillo'], ['Luis Coronado Chapa', 8, 8, 0, '0%', 'Verde'], ['Luisa Roybal Mata', 10, 8, 2, '38%', 'Amarillo'], ['Guadalupe Peralta Montalvo', 14, 7, 7, '29%', 'Amarillo'], ['Víctor Rascón Madrigal', 9, 7, 2, '14%', 'Verde'],
] as const
function Kpi({ title, value, icon }: { title: string; value: string; icon: 'users'|'map'|'flag'|'help' }) { const Icon = icon === 'users' ? Users : icon === 'map' ? Map : icon === 'flag' ? Flag : CircleHelp; return <div className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-2"><p className="text-xs font-medium uppercase tracking-wide text-gray-500">{title}</p><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-slate-900 text-white"><Icon className="h-4 w-4" /></span></div><p className="mt-2 text-2xl font-semibold text-gray-900">{value}</p></div> }
export default function Lideres() {
  const { navigate } = useApp()
  useEffect(() => {
    const onClick = (event: MouseEvent) => {
      const target = event.target as HTMLElement
      if (target.textContent?.trim() === 'Directorio' && target.closest('.mt-4')) {
        event.preventDefault()
        navigate('lider-directorio')
      }
    }
    document.addEventListener('click', onClick)
    return () => document.removeEventListener('click', onClick)
  }, [navigate])
  const [metric, setMetric] = useState('barrio'); const [leader, setLeader] = useState('Alberto Armendáriz Vera')
  return <main className="flex-1 overflow-y-auto p-6"><div className="mx-auto max-w-[1400px]"><div className="mb-6"><h1 className="text-xl font-semibold text-gray-900">Líder</h1><p className="text-sm text-gray-500">Dashboard y directorio — promueve o quita el rol desde la tabla</p><div className="mt-4 flex gap-6 border-b border-gray-200"><a className="border-b-2 border-blue-600 px-1 pb-3 text-sm font-medium text-blue-600">Dashboard</a><a className="border-b-2 border-transparent px-1 pb-3 text-sm font-medium text-gray-500">Directorio</a></div></div><div className="space-y-8">
    <section><div className="grid grid-cols-2 gap-4 md:grid-cols-4"><Kpi title="Total de líderes" value="60" icon="users" /><Kpi title="Circunscripción Inválida" value="Ver detalle" icon="map" /><Kpi title="Cumplimiento de Metas" value="Ver detalle" icon="flag" /><Kpi title="Alerta de decisión" value="Ver detalle" icon="help" /></div><div className="mt-4 rounded-xl border border-gray-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold text-gray-800">Gestión individual del líder</p><p className="text-xs text-gray-400">Equipo de 106 simpatizante(s) — solo residentes de Valledupar</p></div><div className="flex flex-wrap gap-2"><select value={leader} onChange={e=>setLeader(e.target.value)} className="rounded-lg border border-gray-300 px-2 py-1 text-xs">{lideres.map(x=><option key={x[0]}>{x[0]}</option>)}</select><select value={metric} onChange={e=>setMetric(e.target.value)} className="rounded-lg border border-gray-300 px-2 py-1 text-xs"><option value="barrio">Simpatizantes por barrio</option><option value="corregimiento">Simpatizantes por corregimiento</option><option value="puesto">Simpatizantes por puesto de votación</option><option value="validez">Validez y nivel de decisión</option><option value="avance">Avance de meta</option></select></div></div><div className="mt-4 space-y-2">{barrios.map((name,i)=><div key={name} className="flex items-center gap-3 text-xs"><span className="w-36 shrink-0 text-right text-gray-500">{name}</span><div className="h-6 flex-1 rounded bg-gray-50"><div className="h-6 rounded" style={{width:`${100-i*8}%`, backgroundColor: coloresBarrios[i]}} /></div><span className="w-8 text-gray-500">{106-i*9}</span></div>)}</div></div></section>
    <section><div className="mb-1 flex items-center gap-2"><p className="text-sm font-semibold text-gray-700">Alertas de calidad de dato</p><span className="rounded-full bg-slate-900 px-2 py-0.5 text-xs font-semibold text-white">8</span></div><p className="mb-3 text-xs text-gray-400">Vista general de los líderes con alguna alerta — incluye datos fuera de jurisdicción, puesto/mesa sin diligenciar y teléfonos duplicados.</p><div className="overflow-hidden rounded-xl border border-gray-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-900 text-xs uppercase tracking-wide text-white"><tr><th className="px-4 py-2.5">Líder</th><th className="px-4 py-2.5 text-center">N°</th><th className="px-4 py-2.5">Motivos</th></tr></thead><tbody className="divide-y divide-gray-100">{['Víctor Rascón Madrigal','Jordi Gámez Llamas','Santiago Estévez Delgadillo','Josep Ramírez Naranjo','Joaquín Delafuente Pacheco','Luisa Roybal Mata','Carlota Moya Reynoso','Martín Irizarry Burgos'].map((x,i)=><tr key={x}><td className="px-4 py-2.5 font-medium text-gray-800">{x}</td><td className="px-4 py-2.5 text-center"><span className="rounded-full bg-blue-50 px-2 py-0.5 text-xs font-semibold text-blue-700">1</span></td><td className="px-4 py-2.5 text-gray-600">{i%2?'1 teléfono repetido entre simpatizantes de su equipo':'Datos fuera de circunscripción — revisar información'}</td></tr>)}</tbody></table></div></section>
    <section><div className="mb-1 flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><p className="text-sm font-semibold text-gray-700">Ranking de Rendimiento de Líderes</p><span className="rounded-full bg-emerald-50 px-2 py-0.5 text-[11px] font-semibold text-emerald-700">7 Verde</span><span className="rounded-full bg-amber-50 px-2 py-0.5 text-[11px] font-semibold text-amber-700">31 Amarillo</span><span className="rounded-full bg-red-50 px-2 py-0.5 text-[11px] font-semibold text-red-700">22 Rojo</span></div><button className="flex items-center gap-1 text-xs font-medium text-blue-600 hover:underline">Ver los 60 líderes <ArrowRight className="h-3 w-3" /></button></div><p className="mb-3 text-xs text-gray-400">Ordenado por votos válidos aportados — el semáforo compara a cada líder contra el promedio de la campaña.</p><div className="overflow-x-auto rounded-xl border border-gray-200 bg-white"><table className="w-full text-left text-xs"><thead className="bg-gray-50 uppercase tracking-wide text-gray-500"><tr>{['#','Líder','Registrados','Válidos','Inválidos','% Indecisos','Conflicto','Estado'].map(h=><th key={h} className="px-3 py-2 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{lideres.map((x,i)=><tr key={x[0]} className="hover:bg-gray-50"><td className="px-3 py-2 text-gray-600">{i+1}</td><td className="px-3 py-2 font-medium text-gray-900">{x[0]}</td><td className="px-3 py-2 text-gray-600">{x[1]}</td><td className="px-3 py-2 text-gray-600">{x[2]}</td><td className="px-3 py-2 text-gray-600">{x[3]}</td><td className="px-3 py-2 text-gray-600">{x[4]}</td><td className="px-3 py-2 text-gray-600">{i<4?'1':'—'}</td><td className="px-3 py-2"><span className={`rounded-full px-2 py-0.5 text-[11px] font-medium ${x[5]==='Verde'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{x[5]}</span></td></tr>)}</tbody></table></div></section>
    <section><div className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold text-gray-800">Panorama grupal de líderes</p><p className="text-xs text-gray-400">Cómo se agrupan los líderes según su desempeño — haz clic en una barra para ver el directorio</p></div><select className="rounded-lg border border-gray-300 px-2 py-1 text-xs"><option>Rango de votos</option><option>Líderes por puesto de votación</option><option>Por Padrino</option></select></div><p className="mb-1 mt-3 text-[11px] text-gray-400">Haz clic en una barra para ver el detalle.</p><div className="flex h-72 items-end justify-between gap-2 border-b border-l border-gray-300 px-4 pt-4">{[['Hasta 5',1],['6–10',19],['11–15',1],['16–20',1],['21–30',1],['31–50',1],['51–70',1],['71–100',1],['100+',1]].map(([label,value])=><button key={String(label)} type="button" className="group flex h-full flex-1 flex-col items-center justify-end gap-2" title={`Líderes: ${value}`}><span className="text-xs text-gray-500 opacity-0 group-hover:opacity-100">{value}</span><span className="w-full rounded-t bg-blue-600 transition hover:bg-blue-700" style={{height:`${Number(value)/19*88+4}%`}} /><span className="w-16 -rotate-45 origin-top text-[11px] text-gray-500">{label}</span></button>)}</div><div className="mt-4 flex items-center justify-center gap-2 text-xs text-blue-600"><span className="h-3 w-3 rounded-sm bg-blue-600" /> Líderes</div></div></section>
  </div></div></main>
}
