// @ts-nocheck
import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { Flag, List, Map, Megaphone, type LucideIcon } from 'lucide-react'
import { useApp } from '../../../store'
import Directorio from './DirectorioPage'
import { BARRIOS, COMUNAS, INTERESES } from '../../../data'
import { Bars } from '../../../components/ui'

const Card = ({ children }: { children: ReactNode }) => <div className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm">{children}</div>

export default function Simpatizantes() {
  const { simpatizantesApi, cargarSimpatizantesApi, irADirectorio, navigate } = useApp()
  const [tab, setTab] = useState<'dashboard' | 'directorio'>(window.location.pathname.endsWith('/directorio') ? 'directorio' : 'dashboard')
  useEffect(() => { void cargarSimpatizantesApi() }, [cargarSimpatizantesApi])
  const validos = simpatizantesApi.filter((p) => p.departamento === 'Cesar' && p.municipio === 'Valledupar')
  const metrics = useMemo(() => { const total = simpatizantesApi.length; const completos = simpatizantesApi.filter((p) => p.puesto && p.mesa).length; return { total, validos: validos.length, invalidos: total - validos.length, riesgo: simpatizantesApi.filter((p) => p.nivelVoto === 'Indeciso').length, completitud: total ? Math.round(completos / total * 100) : 0 } }, [simpatizantesApi, validos.length])
  const cards = [['Total Simpatizantes Registrados', metrics.total, 'Conteo global bruto · 16 inactivo(s) excluido(s)', 'text-gray-900'], ['Votos Válidos en Valledupar', metrics.validos, `${metrics.total ? Math.round(metrics.validos / metrics.total * 100) : 0}% del total`, 'text-emerald-600'], ['Votos Inválidos / Fuera de Circunscripción', metrics.invalidos, `${metrics.total ? Math.round(metrics.invalidos / metrics.total * 100) : 0}% del total`, 'text-red-600'], ['Votos Indecisos / En Riesgo', metrics.riesgo, `${metrics.validos ? Math.round(metrics.riesgo / metrics.validos * 100) : 0}% de los válidos`, 'text-amber-600'], ['Completitud de Datos Electorales', `${metrics.completitud}%`, 'Con puesto y mesa asignados', 'text-emerald-600']] as const
  const duplicateRows = ['491013322|Rebeca Tórrez Niño|2026-01-30 · Teresa Mena Bañuelos|2026-02-03 · Luisa Roybal Mata', '1047877320|Hernán Concepción Feliciano|2026-02-12 · Guillermina Escamilla Nájera|2026-03-28 · Miguel Serna Riojas', '994214171|María Duarte Valles|2026-03-01 · Norma Solano Naranjo|2026-04-21 · Guillermo Abeyta Garica']
  const duplicates = <section><p className="mb-3 text-sm font-semibold text-gray-700">Mesa de Control y Paternidad de Duplicados</p><div className="overflow-hidden rounded-xl border border-gray-200 bg-white"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase tracking-wide text-gray-500"><tr>{['Cédula', 'Nombre', 'Primer registro', 'Segundo registro', 'Acciones'].map((h) => <th key={h} className="whitespace-nowrap px-4 py-2.5 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{duplicateRows.map((row) => { const [cedula, nombre, primero, segundo] = row.split('|'); return <tr key={cedula} className="hover:bg-gray-50"><td className="whitespace-nowrap px-4 py-3 text-gray-600">{cedula}</td><td className="whitespace-nowrap px-4 py-3 text-gray-600">{nombre}</td><td className="whitespace-nowrap px-4 py-3 text-gray-600">{primero}</td><td className="whitespace-nowrap px-4 py-3 text-gray-600">{segundo}</td><td className="whitespace-nowrap px-4 py-3 text-gray-600"><button type="button" className="rounded-lg border border-gray-300 px-2 py-1 text-xs font-medium text-gray-700 hover:bg-gray-50">Asignar</button>{' '}<button type="button" className="rounded-lg border border-gray-300 px-2 py-1 text-xs font-medium text-red-600 hover:bg-red-50">Descartar</button></td></tr> })}</tbody></table></div></div></section>
  const chart = (title: string, subtitle: string, data: { label: string; value: number; color: string }[]) => <>{<Card><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-gray-800">{title}</p><p className="text-xs text-gray-400">{subtitle}</p></div>{title === 'Votos Válidos por Comuna de Votación' && <select className="rounded-lg border border-gray-300 px-2 py-1 text-xs outline-none focus:border-blue-500" defaultValue="comunaVotacion"><option value="comunaVotacion">Votos Válidos por Comuna de Votación</option><option value="corregimientoVotacion">Votos Válidos por Corregimiento de Votación</option><option value="comunaResidencia">Distribución por Comuna de Residencia</option><option value="corregimientoResidencia">Distribución por Corregimiento de Residencia</option></select>}{title === 'Intereses y Temas Predominantes' && <select className="rounded-lg border border-gray-300 px-2 py-1 text-xs outline-none focus:border-blue-500" defaultValue="intereses"><option value="intereses">Intereses y Temas Predominantes</option><option value="gruposSociales">Distribución por Grupos Sociales</option><option value="academico">Nivel Académico y Ocupación</option></select>}{title === 'Top Barrios con mayor volumen de votos válidos' && <select className="rounded-lg border border-gray-300 px-2 py-1 text-xs outline-none focus:border-blue-500" defaultValue="topBarrios"><option value="topBarrios">Top Barrios con más votos válidos</option><option value="topCorregimientos">Top Corregimientos con más votos válidos</option><option value="rankingPuestosUrbanos">Ranking de Puestos de Votación (zona urbana)</option><option value="rankingPuestosRurales">Ranking de Puestos de Votación (zona rural)</option><option value="destinoInvalidos">Destino de Votos Inválidos</option></select>}</div><p className="mb-1 mt-3 text-[11px] text-gray-400">Haz clic en una barra para ver el detalle.</p><Bars data={data} height={245} /></Card>}{title === 'Intereses y Temas Predominantes' && duplicates}</>
  const comunas = COMUNAS.map((label) => ({ label, value: validos.filter((p) => p.comuna === label).length, color: '#2563eb' })).sort((a, b) => b.value - a.value)
  const barrios = BARRIOS.map((label) => ({ label, value: validos.filter((p) => p.barrio === label).length, color: '#11998e' })).sort((a, b) => b.value - a.value).slice(0, 15)
  const intereses = INTERESES.map((label) => ({ label, value: simpatizantesApi.filter((p) => p.intereses.includes(label)).length, color: '#7c3aed' })).sort((a, b) => b.value - a.value)
  const healthCards: [string, LucideIcon][] = [[`Simpatizantes en Conflicto — 32`, Flag], [`Fuga Territorial — ${metrics.invalidos}`, Map], ['Datos Incompletos — 83', List], ['Concentración Telefónica — 12', Megaphone]]
  return <main className="flex-1 overflow-y-auto p-6"><div className="mb-6"><h1 className="text-xl font-semibold text-gray-900">Simpatizante</h1><p className="text-sm text-gray-500">Directorio y dashboard analítico de simpatizantes</p><div className="mt-4 flex gap-6 border-b border-gray-200">{(['dashboard', 'directorio'] as const).map((item) => <button key={item} type="button" onClick={() => { setTab(item); navigate(item === 'dashboard' ? 'simpatizantes' : 'directorio') }} className={`border-b-2 px-1 pb-3 text-sm font-medium ${tab === item ? 'border-blue-600 text-blue-600' : 'border-transparent text-gray-500 hover:text-gray-700'}`}>{item === 'dashboard' ? 'Dashboard' : 'Directorio'}</button>)}</div></div>{tab === 'directorio' ? <Directorio /> : <div className="space-y-8"><section><p className="mb-3 text-sm font-semibold text-gray-700">Panorama Electoral</p><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-5">{cards.map(([title, value, detail, color]) => <Card key={title}><p className="text-xs font-medium uppercase tracking-wide text-gray-500">{title}</p><button type="button" onClick={() => irADirectorio({})} className={`mt-2 text-2xl font-semibold ${color}`}>{value}</button><p className="mt-1 text-xs text-gray-400">{detail}</p></Card>)}</div></section><section><p className="mb-3 text-sm font-semibold text-gray-700">Salud e Integridad de la Base de Datos</p><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[`Simpatizantes en Conflicto — 32`, Flag], [`Fuga Territorial — ${metrics.invalidos}`, Map], ['Datos Incompletos — 83', List], ['Concentración Telefónica — 12', Megaphone]].map(([title, Icon]) => <button key={String(title)} type="button" onClick={() => irADirectorio({})} className="group flex flex-col rounded-xl border border-gray-200 bg-white p-4 text-left shadow-sm transition hover:border-blue-300 hover:bg-blue-50/40"><div className="flex items-start justify-between gap-2"><p className="text-xs font-medium uppercase tracking-wide text-gray-500">{title}</p><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-red-50 text-red-600"><Icon className="h-4 w-4" /></span></div><p className="mt-2 text-sm font-semibold text-blue-700">Ver detalle →</p></button>)}</div></section><section><p className="mb-3 text-sm font-semibold text-gray-700">Análisis Territorial</p>{chart('Votos Válidos por Comuna de Votación', 'Solo simpatizantes con validez Válido', comunas)}</section><section><p className="mb-3 text-sm font-semibold text-gray-700">Penetración Geográfica Detallada</p>{chart('Top Barrios con mayor volumen de votos válidos', 'Solo simpatizantes con validez Válido', barrios)}</section><section><p className="mb-3 text-sm font-semibold text-gray-700">Caracterización Social y Discurso</p>{chart('Intereses y Temas Predominantes', 'Caracterización declarada por los propios simpatizantes', intereses)}</section></div>}</main>
}
